Trailer/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('home.urls') ,name='home'),
    url(r'^home/',include('home.urls') ,name='home'),
    url(r'^movie/',include('movie.urls') ,name='movie'),
    url(r'^game/',include('game.urls') ,name='game'),
    url(r'^aboutus/',include('aboutus.urls') ,name='game'),
]

aboutus/urls.py
from django.conf.urls import url
from aboutus import views

app_name='aboutus'
urlpatterns = [

    url(r'^$',views.Aboutus.as_view() ,name='home'),

]

game/urls.py
from django.conf.urls import url
from game import views

app_name='game'
urlpatterns = [

    url(r'^$',views.Home.as_view() ,name='home'),
    url(r'^(?P<pk>[0-9]+)/$',views.Detail.as_view(),name='detail')
]

home/urls.py
from django.conf.urls import url
from . import views

app_name='home'
urlpatterns = [

    url(r'^$',views.Homeview.as_view() ,name='home')

]

movie/urls.py
from django.conf.urls import url
from . import views

app_name='movie'
urlpatterns = [

    url(r'^$',views.Home.as_view() ,name='home'),
    url(r'^(?P<pk>[0-9]+)/$',views.Detail.as_view(),name='detail')
]

aboutus/models.py
from django.db import models

# Create your models here.
class About(models.Model):

    def __str__(self):
        return self.title

game/models.py
from django.db import models

class Game_Details(models.Model):
    title=models.CharField(max_length=50)
    release_date=models.CharField(max_length=50)
    video_link=models.CharField(max_length=1000)
    banner=models.CharField(max_length=1000,default='#')

    def __str__(self):
        return self.title
class Game_carousel(models.Model):
    caption=models.CharField(max_length=50)
    image_link=models.CharField(max_length=200)

    def __str__(self):
        return self.caption

home/models.py
from django.db import models

# Create your models here.
class Home(models.Model):
    def __str__(self):
        return self.title

movie/models.py
from django.db import models

class Movie_Details(models.Model):
    title=models.CharField(max_length=50)
    release_date=models.CharField(max_length=50)
    video_link=models.CharField(max_length=1000)
    banner=models.CharField(max_length=1000,default='#')

    def __str__(self):
        return self.title

aboutus/views.py
#from django.shortcuts import render
from django.views import generic
from .models import About

class Aboutus(generic.ListView):
    template_name = 'movie/about.html'

    def get_queryset(self):
        return About.objects.all()

game/views.py
#from django.shortcuts import render
from django.views import generic
from .models import Game_Details,Game_carousel

class Home(generic.ListView):
    template_name = 'game/home.html'
    context_object_name = 'object_list'
    #Game_carousel.objects.all()
    def get_queryset(self):
        return Game_Details.objects.all()[::-1]

class Detail(generic.DetailView):
    model = Game_Details
    template_name = 'movie/detail.html'

home/views.py
from django.shortcuts import render
from django.views import generic
from .models import Home

class Homeview(generic.ListView):
    template_name = 'home/home.html'
    context_object_name = 'object_list'

    # Game_carousel.objects.all()
    def get_queryset(self):
        return Home.objects.all()

movie/views.py
from django.views import generic
from .models import Movie_Details
# Create your views here.

class Home(generic.ListView):
    template_name = 'movie/home.html'
    context_object_name = 'object_list'
    def get_queryset(self):
        return Movie_Details.objects.all()[::-1]

class Detail(generic.DetailView):
    model = Movie_Details
    template_name = 'movie/detail.html'

game/templates/game/home.html
{% extends 'movie/base.html' %}
{% block active %}
<li ><a href="{% url 'movie:home' %}">Movies</a></li>
<li class="active"><a href="{% url 'game:home' %}">Games</a></li>
{% endblock %}
{% block body %}


    <ul>


        {% for movie in object_list %}

        <div class="col-lg-2" >
        <div class="panel panel-default">
                     <a href={% url 'game:detail' movie.id %}>
            <div class="panel-body"><img style="height:300px;" src="{{ movie.banner }}" class="img-responsive img-rounded" /></div>
            <div class="panel-footer">{{ movie.title }}</div>
            <div class="panel-footer">{{ movie.release_date }}</div></a>
        </div>
         </div>
        {% endfor %}
    </ul>
{% endblock %}

home/templates/home/home.html
{% extends 'movie/base.html' %}
{% block active %}
<li ><a href="{% url 'movie:home' %}">Movies</a></li>
<li ><a href="{% url 'game:home' %}">Games</a></li>
{% endblock %} }}
{% block aboutcontact %}
<li ><a href="{% url 'aboutus:home' %}">About us</a></li>
                    <li><a href="#">Contact us</a></li>
{% endblock %}

{% block body %}
<div class="container" >
  <h1 style="font-family: 'Orbitron" >Watch Trailers of Latest Movies and Games </h1>
  <div class="row">
    <div class="col-sm-6" style="">
     <a href='{% url 'movie:home' %}' > <p style="font-family: 'Bangers';font-size: 30pt" >Movies</p></a>
    </div>
    <div class="col-sm-6" style="">
      <a href='{% url 'game:home' %}' ><p style="font-family: 'Bangers';font-size: 30pt" >Games</p></a>
    </div>
  </div>
 <div class="row"  >
    <div class="col-sm-6" style="">
        <a href='{% url 'movie:home' %}' >
      <img class="img-rounded" style="width: 400pt" src="https://cdn3.iconfinder.com/data/icons/multimedia/100/play_movie_3-512.png"></a>
    </div>
    <div class="col-sm-6" style="">
        <a href='{% url 'game:home' %}' >
      <img class="img-rounded" style="width: 400pt" src="http://icons.iconarchive.com/icons/dtafalonso/android-lollipop/512/Play-Games-icon.png"></a>
    </div>
  </div>

</div>
{% endblock %}

movie/templates/movie/about.html
{% extends 'movie/base.html' %}
{% block active %}
<li ><a href="{% url 'movie:home' %}">Movies</a></li>
<li ><a href="{% url 'game:home' %}">Games</a></li>
{% endblock %} }}
{% block body %}
<h1 >About us</h1>
{% endblock %}
{% block aboutcontact %}
<li class="active"><a href="{% url 'aboutus:home' %}">About us</a></li>
                    <li><a href="#">Contact us</a></li>
{% endblock %}

movie/templates/movie/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Baloo+Tamma" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'movie/style.css' %}">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>


    </style>
    <title>Trailz</title>
     <link rel="stylesheet" type="text/css" href="#"/>
</head>
<body>
    <nav class="navbar navbar-inverse"style="font-family: 'Anton'">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topnavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home:home' %}">Trailz</a>
            </div>
            <div class="collapse navbar-collapse" id="topnavbar">
                <ul class="nav navbar-nav">
                    {% block active %}
                    <li class="active"><a href="{% url 'movie:home' %}">Movies</a></li>

                    <li><a href="{% url 'game:home' %}">Games</a></li>
                    {% endblock %}
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="" />
                        <button type="submit" class="btn btn-default">Search</button>

                    </div>

                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% block aboutcontact %}
                    <li><a href="{% url 'aboutus:home' %}">About us</a></li>
                    <li><a href="#">Contact us</a></li>
                    {% endblock %}

                </ul>
            </div>
        </div>
    </nav>
{% block body %}

{% endblock %}


</body>
<footer class="footer">Watch Trailers of Movies and Games</footer>
</html>

movie/templates/movie/detail.html
{% extends 'movie/base.html' %}
{% block body %}

            <div class="col-lg-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <img src="{{ object.banner }}" class="img-responsive img-rounded">
                         <h2>{{ object.title }}</h2>
                         <h4>{{ object.release_date }}</h4>
                    </div>
                </div>
            </div>
            <div class="col-lg-7">
            <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="{{ object.video_link }}"></iframe>
                        </div>
                    </div>
                </div>
            </div>


{% endblock %}

movie/templates/movie/home.html
{% extends 'movie/base.html' %}

{% block body %}
  
    <ul>

        {% for movie in object_list %}
       <!--
        <li>
            <a href="{% url 'movie:detail' movie.id %}">{{ movie.title }}</a>

        </li>-->
        <div class="col-lg-2" >
        <div class="panel panel-default">
                     <a href={% url 'movie:detail' movie.id %}>
            <div class="panel-body"><img src="{{ movie.banner }}" class="img-responsive img-rounded" /></div>
            <div class="panel-footer">{{ movie.title }}</div>
            <div class="panel-footer">{{ movie.release_date }}</div></a>
        </div>
         </div>
        {% endfor %}
    </ul>
{% endblock %}